"""
Team name alias dictionary for cross-bookmaker normalization.

Maps common abbreviations and short forms used by different bookmakers
to a single canonical team name, enabling cross-bookmaker event matching.

HDLinea tends to use short city abbreviations: "GOLDEN ST", "LA LAKERS"
Betcris tends to use full names:              "Golden State Warriors"
JuancitoSport uses BOSS format, often like:  "Golden State"
"""

# ── Location/city abbreviations expanded before sport-specific lookup ─────────
LOCATION_ALIASES: dict[str, str] = {
    "la":          "los angeles",
    "ny":          "new york",
    "nj":          "new jersey",
    "gs":          "golden state",
    "golden st":   "golden state",
    "sf":          "san francisco",
    "kc":          "kansas city",
    "gb":          "green bay",
    "tb":          "tampa bay",
    "no":          "new orleans",
    "nola":        "new orleans",
    "okc":         "oklahoma city",
    "sa":          "san antonio",
    "phi":         "philadelphia",
    "chi":         "chicago",
    "bos":         "boston",
    "mia":         "miami",
    "atl":         "atlanta",
    "det":         "detroit",
    "den":         "denver",
    "min":         "minnesota",
    "hou":         "houston",
    "dal":         "dallas",
    "mil":         "milwaukee",
    "tor":         "toronto",
    "ind":         "indiana",
    "por":         "portland",
    "sac":         "sacramento",
    "cha":         "charlotte",
    "was":         "washington",
    "wsh":         "washington",
    "cle":         "cleveland",
    "pho":         "phoenix",
    "phx":         "phoenix",
    "orl":         "orlando",
    "bkn":         "brooklyn",
    "buf":         "buffalo",
    "ott":         "ottawa",
    "edm":         "edmonton",
    "cal":         "calgary",
    "col":         "colorado",
    "car":         "carolina",
    "nsh":         "nashville",
    "stl":         "st louis",
    "pit":         "pittsburgh",
    "cin":         "cincinnati",
    "sea":         "seattle",
    "mem":         "memphis",
    "uta":         "utah",
    "van":         "vancouver",
}

# ── Per-sport full canonical expansions ───────────────────────────────────────
# Key = normalized short form (already lowercased, no special chars)
# Value = canonical long name (also normalized, no accents, lowercase)
SPORT_TEAM_ALIASES: dict[str, dict[str, str]] = {
    "NBA": {
        # Single-word nicknames
        "lakers":             "los angeles lakers",
        "clippers":           "los angeles clippers",
        "warriors":           "golden state warriors",
        "celtics":            "boston celtics",
        "heat":               "miami heat",
        "bulls":              "chicago bulls",
        "knicks":             "new york knicks",
        "nets":               "brooklyn nets",
        "sixers":             "philadelphia 76ers",
        "76ers":              "philadelphia 76ers",
        "raptors":            "toronto raptors",
        "bucks":              "milwaukee bucks",
        "pacers":             "indiana pacers",
        "cavaliers":          "cleveland cavaliers",
        "cavs":               "cleveland cavaliers",
        "pistons":            "detroit pistons",
        "hawks":              "atlanta hawks",
        "hornets":            "charlotte hornets",
        "wizards":            "washington wizards",
        "magic":              "orlando magic",
        "thunder":            "oklahoma city thunder",
        "nuggets":            "denver nuggets",
        "timberwolves":       "minnesota timberwolves",
        "wolves":             "minnesota timberwolves",
        "jazz":               "utah jazz",
        "suns":               "phoenix suns",
        "kings":              "sacramento kings",
        "blazers":            "portland trail blazers",
        "spurs":              "san antonio spurs",
        "rockets":            "houston rockets",
        "mavericks":          "dallas mavericks",
        "mavs":               "dallas mavericks",
        "grizzlies":          "memphis grizzlies",
        "pelicans":           "new orleans pelicans",
        # Abbreviated city forms (as HDLinea uses them)
        "la lakers":          "los angeles lakers",
        "la clippers":        "los angeles clippers",
        "ny knicks":          "new york knicks",
        "gs warriors":        "golden state warriors",
        "golden st":          "golden state warriors",
        "golden st warriors": "golden state warriors",
        "okc thunder":        "oklahoma city thunder",
        "oklahoma city":      "oklahoma city thunder",
        "new orleans":        "new orleans pelicans",
        "san antonio":        "san antonio spurs",
        "portland":           "portland trail blazers",
        "trail blazers":      "portland trail blazers",
        "minnesota":          "minnesota timberwolves",
        "indiana":            "indiana pacers",
        "utah":               "utah jazz",
    },
    "NFL": {
        "patriots":           "new england patriots",
        "chiefs":             "kansas city chiefs",
        "bills":              "buffalo bills",
        "dolphins":           "miami dolphins",
        "jets":               "new york jets",
        "ravens":             "baltimore ravens",
        "steelers":           "pittsburgh steelers",
        "browns":             "cleveland browns",
        "bengals":            "cincinnati bengals",
        "texans":             "houston texans",
        "colts":              "indianapolis colts",
        "jaguars":            "jacksonville jaguars",
        "titans":             "tennessee titans",
        "broncos":            "denver broncos",
        "raiders":            "las vegas raiders",
        "chargers":           "los angeles chargers",
        "packers":            "green bay packers",
        "bears":              "chicago bears",
        "vikings":            "minnesota vikings",
        "lions":              "detroit lions",
        "cowboys":            "dallas cowboys",
        "giants":             "new york giants",
        "eagles":             "philadelphia eagles",
        "commanders":         "washington commanders",
        "49ers":              "san francisco 49ers",
        "niners":             "san francisco 49ers",
        "seahawks":           "seattle seahawks",
        "rams":               "los angeles rams",
        "cardinals":          "arizona cardinals",
        "saints":             "new orleans saints",
        "buccaneers":         "tampa bay buccaneers",
        "bucs":               "tampa bay buccaneers",
        "panthers":           "carolina panthers",
        "falcons":            "atlanta falcons",
        "new england":        "new england patriots",
        "green bay":          "green bay packers",
        "las vegas":          "las vegas raiders",
        "kansas city":        "kansas city chiefs",
        "new orleans":        "new orleans saints",
        "tampa bay":          "tampa bay buccaneers",
        "san francisco":      "san francisco 49ers",
    },
    "NHL": {
        "bruins":             "boston bruins",
        "sabres":             "buffalo sabres",
        "red wings":          "detroit red wings",
        "panthers":           "florida panthers",
        "canadiens":          "montreal canadiens",
        "habs":               "montreal canadiens",
        "senators":           "ottawa senators",
        "lightning":          "tampa bay lightning",
        "maple leafs":        "toronto maple leafs",
        "leafs":              "toronto maple leafs",
        "hurricanes":         "carolina hurricanes",
        "blue jackets":       "columbus blue jackets",
        "capitals":           "washington capitals",
        "caps":               "washington capitals",
        "blackhawks":         "chicago blackhawks",
        "avalanche":          "colorado avalanche",
        "avs":                "colorado avalanche",
        "wild":               "minnesota wild",
        "predators":          "nashville predators",
        "preds":              "nashville predators",
        "blues":              "st louis blues",
        "jets":               "winnipeg jets",
        "ducks":              "anaheim ducks",
        "flames":             "calgary flames",
        "oilers":             "edmonton oilers",
        "kings":              "los angeles kings",
        "sharks":             "san jose sharks",
        "golden knights":     "vegas golden knights",
        "knights":            "vegas golden knights",
        "rangers":            "new york rangers",
        "islanders":          "new york islanders",
        "flyers":             "philadelphia flyers",
        "penguins":           "pittsburgh penguins",
        "coyotes":            "arizona coyotes",
        "canucks":            "vancouver canucks",
        "stars":              "dallas stars",
        "kraken":             "seattle kraken",
        "tampa bay":          "tampa bay lightning",
        "new york rangers":   "new york rangers",
        "new york islanders": "new york islanders",
        "vegas":              "vegas golden knights",
        "winnipeg":           "winnipeg jets",
        "florida":            "florida panthers",
        "montreal":           "montreal canadiens",
        "st louis":           "st louis blues",
        "columbus":           "columbus blue jackets",
        "colorado":           "colorado avalanche",
        "minnesota":          "minnesota wild",
        "nashville":          "nashville predators",
        "anaheim":            "anaheim ducks",
        "calgary":            "calgary flames",
        "edmonton":           "edmonton oilers",
        "vancouver":          "vancouver canucks",
        "ottawa":             "ottawa senators",
        "carolina":           "carolina hurricanes",
        "washington":         "washington capitals",
    },
    "MLB": {
        "red sox":            "boston red sox",
        "yankees":            "new york yankees",
        "mets":               "new york mets",
        "blue jays":          "toronto blue jays",
        "rays":               "tampa bay rays",
        "orioles":            "baltimore orioles",
        "white sox":          "chicago white sox",
        "cubs":               "chicago cubs",
        "guardians":          "cleveland guardians",
        "indians":            "cleveland guardians",
        "tigers":             "detroit tigers",
        "royals":             "kansas city royals",
        "twins":              "minnesota twins",
        "astros":             "houston astros",
        "angels":             "los angeles angels",
        "athletics":          "oakland athletics",
        "mariners":           "seattle mariners",
        "rangers":            "texas rangers",
        "braves":             "atlanta braves",
        "marlins":            "miami marlins",
        "phillies":           "philadelphia phillies",
        "pirates":            "pittsburgh pirates",
        "cardinals":          "st louis cardinals",
        "brewers":            "milwaukee brewers",
        "reds":               "cincinnati reds",
        "rockies":            "colorado rockies",
        "dodgers":            "los angeles dodgers",
        "padres":             "san diego padres",
        "giants":             "san francisco giants",
        "diamondbacks":       "arizona diamondbacks",
        "dbacks":             "arizona diamondbacks",
        "nationals":          "washington nationals",
        "nats":               "washington nationals",
        "new york yankees":   "new york yankees",
        "new york mets":      "new york mets",
        "boston":             "boston red sox",
        "chicago cubs":       "chicago cubs",
        "chicago white sox":  "chicago white sox",
        "cleveland":          "cleveland guardians",
        "toronto":            "toronto blue jays",
        "tampa bay":          "tampa bay rays",
        "baltimore":          "baltimore orioles",
        "kansas city":        "kansas city royals",
        "minnesota":          "minnesota twins",
        "houston":            "houston astros",
        "seattle":            "seattle mariners",
        "texas":              "texas rangers",
        "atlanta":            "atlanta braves",
        "miami":              "miami marlins",
        "pittsburgh":         "pittsburgh pirates",
        "milwaukee":          "milwaukee brewers",
        "cincinnati":         "cincinnati reds",
        "colorado":           "colorado rockies",
        "san diego":          "san diego padres",
        "arizona":            "arizona diamondbacks",
        "washington":         "washington nationals",
        "oakland":            "oakland athletics",
        "san francisco":      "san francisco giants",
    },
    "NCAAB": {
        # Common abbreviations used in NCAAB betting lines
        "duke":               "duke blue devils",
        "unc":                "north carolina tar heels",
        "north carolina":     "north carolina tar heels",
        "tar heels":          "north carolina tar heels",
        "blue devils":        "duke blue devils",
        "kansas":             "kansas jayhawks",
        "jayhawks":           "kansas jayhawks",
        "kentucky":           "kentucky wildcats",
        "wildcats":           "kentucky wildcats",
        "villanova":          "villanova wildcats",
        "gonzaga":            "gonzaga bulldogs",
        "bulldogs":           "gonzaga bulldogs",
        "michigan st":        "michigan state spartans",
        "michigan state":     "michigan state spartans",
        "spartans":           "michigan state spartans",
        "ohio st":            "ohio state buckeyes",
        "ohio state":         "ohio state buckeyes",
        "buckeyes":           "ohio state buckeyes",
        "indiana":            "indiana hoosiers",
        "hoosiers":           "indiana hoosiers",
        "purdue":             "purdue boilermakers",
        "iowa":               "iowa hawkeyes",
        "hawkeyes":           "iowa hawkeyes",
        "houston":            "houston cougars",
        "cougars":            "houston cougars",
        "connecticut":        "connecticut huskies",
        "uconn":              "connecticut huskies",
        "huskies":            "connecticut huskies",
        "baylor":             "baylor bears",
        "alabama":            "alabama crimson tide",
        "tennessee":          "tennessee volunteers",
        "vols":               "tennessee volunteers",
        "florida":            "florida gators",
        "gators":             "florida gators",
        "arkansas":           "arkansas razorbacks",
        "lsu":                "lsu tigers",
        "creighton":          "creighton bluejays",
        "marquette":          "marquette golden eagles",
        "san diego st":       "san diego state aztecs",
        "sdsu":               "san diego state aztecs",
        "st johns":           "st johns red storm",
    },
    "SOC": {
        # Soccer — common DR-market teams (Latin America / Europe)
        "real madrid":        "real madrid",
        "barcelona":          "fc barcelona",
        "barca":              "fc barcelona",
        "fc barcelona":       "fc barcelona",
        "atletico":           "atletico madrid",
        "atletico madrid":    "atletico madrid",
        "man united":         "manchester united",
        "man utd":            "manchester united",
        "manchester utd":     "manchester united",
        "man city":           "manchester city",
        "manchester city":    "manchester city",
        "liverpool":          "liverpool fc",
        "chelsea":            "chelsea fc",
        "arsenal":            "arsenal fc",
        "tottenham":          "tottenham hotspur",
        "spurs":              "tottenham hotspur",
        "juventus":           "juventus fc",
        "inter milan":        "inter milan",
        "internazionale":     "inter milan",
        "ac milan":           "ac milan",
        "milan":              "ac milan",
        "psg":                "paris saint germain",
        "paris sg":           "paris saint germain",
        "paris saint germain": "paris saint germain",
        "bayern":             "bayern munich",
        "bayern munich":      "bayern munich",
        "dortmund":           "borussia dortmund",
        "bvb":                "borussia dortmund",
    },
    "EUROL": {
        # EuroLeague Basketball
        "real madrid":        "real madrid basketball",
        "barcelona":          "fc barcelona basketball",
        "fenerbahce":         "fenerbahce beko",
        "olympiacos":         "olympiacos piraeus",
        "panathinaikos":      "panathinaikos athens",
        "anadolu efes":       "anadolu efes istanbul",
        "efes":               "anadolu efes istanbul",
        "cska":               "cska moscow",
        "cska moscow":        "cska moscow",
        "maccabi":            "maccabi tel aviv",
        "zalgiris":           "zalgiris kaunas",
        "alba berlin":        "alba berlin",
        "alba":               "alba berlin",
        "monaco":             "as monaco basketball",
        "virtus bologna":     "virtus bologna",
        "virtus":             "virtus bologna",
        "red star":           "crvena zvezda",
        "milan":              "ea7 emporio armani milan",
        "armani milan":       "ea7 emporio armani milan",
    },
}


def expand_team_alias(name: str, sport_code: str = "") -> str:
    """
    Expand a normalized team name using the alias dictionary.

    Process:
    1. Apply basic normalization (already done before calling this)
    2. Check sport-specific full alias table
    3. Expand leading city abbreviation (e.g., "la" -> "los angeles")
    4. Re-check sport alias table after city expansion
    5. Return canonical form, or original if no match found

    Args:
        name:       Already normalized (lowercase, no special chars) team name
        sport_code: Sport code string (NBA, NFL, NHL, MLB, NCAAB, SOC, EUROL)

    Returns:
        Canonical team name (lowercase, no special chars)
    """
    sport_aliases = SPORT_TEAM_ALIASES.get(sport_code.upper(), {})

    # Direct lookup in sport-specific aliases
    if name in sport_aliases:
        return sport_aliases[name]

    # Try expanding a leading city/location abbreviation
    tokens = name.split()
    if len(tokens) >= 2:
        first = tokens[0]
        if first in LOCATION_ALIASES:
            expanded = LOCATION_ALIASES[first] + " " + " ".join(tokens[1:])
            if expanded in sport_aliases:
                return sport_aliases[expanded]
            # Return the location-expanded form even without further alias match
            # so "la lakers" -> "los angeles lakers" (readable canonical form)
            return expanded

    # Single-token location abbreviation with sport context
    if len(tokens) == 1 and tokens[0] in LOCATION_ALIASES:
        return LOCATION_ALIASES[tokens[0]]

    return name
